<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LockerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = Carbon::now('Asia/Jakarta')->format('Y-m-d H:i:s');
        $listlocker = [
            [
                'locker_number' => 'L001',
                'status_locker_id' => '2',
                'location_id' => '1',
                'locker_size' => 'L',
                'status_door' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'locker_number' => 'L002',
                'status_locker_id' => '2',
                'location_id' => '1',
                'locker_size' => 'L',
                'status_door' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'locker_number' => 'L003',
                'status_locker_id' => '2',
                'location_id' => '1',
                'locker_size' => 'L',
                'status_door' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'locker_number' => 'L004',
                'status_locker_id' => '2',
                'location_id' => '1',
                'locker_size' => 'L',
                'status_door' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'locker_number' => 'L005',
                'status_locker_id' => '2',
                'location_id' => '1',
                'locker_size' => 'L',
                'status_door' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'locker_number' => 'L006',
                'status_locker_id' => '2',
                'location_id' => '1',
                'locker_size' => 'XL',
                'status_door' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'locker_number' => 'L007',
                'status_locker_id' => '2',
                'location_id' => '1',
                'locker_size' => 'XL',
                'status_door' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'locker_number' => 'L008',
                'status_locker_id' => '2',
                'location_id' => '1',
                'locker_size' => 'XL',
                'status_door' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'locker_number' => 'L009',
                'status_locker_id' => '2',
                'location_id' => '1',
                'locker_size' => 'XL',
                'status_door' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'locker_number' => 'L010',
                'status_locker_id' => '2',
                'location_id' => '1',
                'locker_size' => 'XL',
                'status_door' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'locker_number' => 'L001',
                'status_locker_id' => '2',
                'location_id' => '2',
                'locker_size' => 'L',
                'status_door' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'locker_number' => 'L002',
                'status_locker_id' => '2',
                'location_id' => '2',
                'locker_size' => 'L',
                'status_door' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'locker_number' => 'L003',
                'status_locker_id' => '2',
                'location_id' => '2',
                'locker_size' => 'L',
                'status_door' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'locker_number' => 'L004',
                'status_locker_id' => '2',
                'location_id' => '2',
                'locker_size' => 'L',
                'status_door' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'locker_number' => 'L005',
                'status_locker_id' => '2',
                'location_id' => '2',
                'locker_size' => 'L',
                'status_door' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'locker_number' => 'L006',
                'status_locker_id' => '2',
                'location_id' => '2',
                'locker_size' => 'XL',
                'status_door' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'locker_number' => 'L007',
                'status_locker_id' => '2',
                'location_id' => '2',
                'locker_size' => 'XL',
                'status_door' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'locker_number' => 'L008',
                'status_locker_id' => '2',
                'location_id' => '2',
                'locker_size' => 'XL',
                'status_door' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'locker_number' => 'L009',
                'status_locker_id' => '2',
                'location_id' => '2',
                'locker_size' => 'XL',
                'status_door' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'locker_number' => 'L010',
                'status_locker_id' => '2',
                'location_id' => '2',
                'locker_size' => 'XL',
                'status_door' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'locker_number' => 'L001',
                'status_locker_id' => '2',
                'location_id' => '3',
                'locker_size' => 'L',
                'status_door' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'locker_number' => 'L002',
                'status_locker_id' => '2',
                'location_id' => '3',
                'locker_size' => 'L',
                'status_door' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'locker_number' => 'L003',
                'status_locker_id' => '2',
                'location_id' => '3',
                'locker_size' => 'L',
                'status_door' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'locker_number' => 'L004',
                'status_locker_id' => '2',
                'location_id' => '3',
                'locker_size' => 'L',
                'status_door' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'locker_number' => 'L005',
                'status_locker_id' => '2',
                'location_id' => '3',
                'locker_size' => 'L',
                'status_door' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'locker_number' => 'L006',
                'status_locker_id' => '2',
                'location_id' => '3',
                'locker_size' => 'XL',
                'status_door' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'locker_number' => 'L007',
                'status_locker_id' => '2',
                'location_id' => '3',
                'locker_size' => 'XL',
                'status_door' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'locker_number' => 'L008',
                'status_locker_id' => '2',
                'location_id' => '3',
                'locker_size' => 'XL',
                'status_door' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'locker_number' => 'L009',
                'status_locker_id' => '2',
                'location_id' => '3',
                'locker_size' => 'XL',
                'status_door' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'locker_number' => 'L010',
                'status_locker_id' => '2',
                'location_id' => '3',
                'locker_size' => 'XL',
                'status_door' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],

        ];

        DB::table('ms_lockers')->insert($listlocker);
    }
}
